# Test all scripts in tests/ and doc compilation
name: main_actions

on: push

jobs:
  test_all_tests:
    runs-on: [ubuntu-latest]
    defaults: 
      run:
        working-directory: ./    
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install python3-tk
      - run: sudo apt install pipx
      - run: pipx install sv-ttk
      - run: pipx install pandas
      - run: pipx install matplotlib
      - run: pipx install typing-extensions
      - run: python3 -m unittest tests/test_gui_window_basic.py -v

  test_documentation:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install python3-sphinx
      - run: pip install sphinx-rtd-theme
      - run: pip install myst-parser
      - run: pip install sphinxcontrib-bibtex
      - run: make html